# Generated by Django 5.0.7 on 2024-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='blog_images')),
                ('title', models.CharField(max_length=100)),
                ('mini_description', models.TextField()),
                ('readingTime', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
