# Generated by Django 5.0.7 on 2024-07-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='specificPropertyImages')),
                ('image2', models.ImageField(upload_to='specificPropertyImages')),
                ('image3', models.ImageField(upload_to='specificPropertyImages')),
                ('image4', models.ImageField(upload_to='specificPropertyImages')),
                ('image5', models.ImageField(upload_to='specificPropertyImages')),
                ('image6', models.ImageField(upload_to='specificPropertyImages')),
                ('image7', models.ImageField(upload_to='specificPropertyImages')),
                ('image8', models.ImageField(upload_to='specificPropertyImages')),
                ('image9', models.ImageField(upload_to='specificPropertyImages')),
                ('image10', models.ImageField(upload_to='specificPropertyImages')),
                ('owner_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
    ]
